app.py
utils/config.py

Clean up some code

---

dev/io_test/producer/producer.py

Not sure how Kafka client works, but re-using the same dictionary can lead to duplicate data being sent if the serialization for the wire is delayed until the flush.
This change creates a new dictionary each time to avoid the possibility of that happening.
Also converted the `get_keys()` into a generator named, `gen_keys_and_urls()` so that a very large list of keys could be generated without requiring large amounts of memory.

Some suggestions to ensure unique data

---

README.md
app.py

Update inventory message

---

dev/README.md
dev/openshift.yml
dev/test-producer-job.yml

Add steps to standup the test framework in OCP4

---

process.py

Add installed products to system_profile

---

utils/config.py

We should have this set as the default for all the dev stuff out there.

Switch the log group to platform-dev

---

app.py
process.py

We grab the satellite ID from branch_info.
If we get a -1 as the remote_branch, we set the satellite_managed fact to `False`, otherwise it's set to `True` and we save the `satellite_id` in a fact

Grab the satellite ID

---

app.py
tests/test_app.py
tests/test_msgs.py

Implement the stalecheck timestamp for inventory

Stalecheck

---

app.py

We're going to use this for the stalecheck

Add reporter field

---

README.md
app.py
dev/full-stack.yml
tests/test_app.py
tests/test_msgs.py

Stable release
* Docs fixes
* Stale Timestamp

Stable 111419

---

app.py
process.py

Support the tags coming in from branch_info
Also enforce the `insights-client` namespace value in `tags.conf`

Support satellite tagging

---

Pipfile
Pipfile.lock
app.py
process.py

Stable Relase

---

Pipfile.lock
mq/produce.py

Need to set ensure_ascii=False when encoding json to keep it from
tripping up on surrogates
Fixes RHCLOUD-5013

Fix unicode issues in yum names

---

Pipfile
Pipfile.lock
app.py
mq/consume.py
mq/produce.py
utils/config.py
utils/metrics.py

Switch to librdkafka

---

src/puptoo/process.py

Use SAP combiner for sap details in system_profile

---

src/puptoo/app.py

Signed-off-by: Jesse Jaggars <jhjaggars@gmail.com>

making sure that we at least try to flush and commit

---

src/puptoo/process.py

This commit finds the SID for each local instance. It then removes
duplicates and sorts the list before adding to the system profile.

add "sap_sids" fact

---

src/puptoo/process.py

Fix a bug in tags formatting

---

setup.py

Install latest insights-core version

---

src/puptoo/process.py

Remove sap instances of 98 and 99 from sys profile

---

src/puptoo/app.py
src/puptoo/process.py
src/puptoo/utils/metrics.py

Add additional metrics

---

src/puptoo/app.py
src/puptoo/utils/metrics.py

Fix a bad metric

---

Dockerfile

Ensure the latest insights-core gets installed

---

src/puptoo/process.py

Dependent on this Schema PR discussion:
https://github.com/RedHatInsights/inventory-schemas/pull/27

Add os name, major, minor release

---

.gitignore

We don't need to check in sonarqube or virtualenv stuff

task: add directories to gitignore

---

Dockerfile

We should just make a happen of updating these packages on build

fix: Update and then clean all installed packages in Dockerfile

---

src/puptoo/process.py

This is in addition to the "installed_packages" not instead of.

DRFT-33 - pass all packages not only max

---

parse_json.py
poetry.lock
pr_check.sh
pyproject.toml
requirements.txt
src/puptoo/process/profile.py

Add a schema validation step to the pr_check process

Schema validation

---

poetry.lock

This includes a fix for insights-core

update: python packages

---

src/puptoo/app.py

HBI is going to begin requiring that systems pass along their owner_id
into the system_profile if they are using cert_auth. This change is
meant to support that effort.
RHCLOUD-12112

feat(sys_profile): Add owner_id based on system CN

---

src/puptoo/process/profile.py

This should sort all of our entries in system profile alphabetically

feat(profile): sort all lists in system_profile

---

src/puptoo/process/profile.py

The product ID parser gives us a set. We can't loop over that, so we're
converting it to a list, then sorting the resulting list

fix(system_profile): Fix bug related to product_ids

---

src/puptoo/process/profile.py

fix(system_profile): fix product_ids to match schema

---

poetry.lock
pyproject.toml
requirements.txt
src/puptoo/utils/puptoo_logging.py

fix: remove the logstash formatter

---

src/puptoo/utils/puptoo_logging.py

fix: use stderr for haberdasher

---

src/puptoo/process/profile.py

Add model name as cpu_model to system profile as requested:
https://issues.redhat.com/browse/HBISPSC-39

Add model name as cpu_model to system profile

---

dev/test-archives/core-base/data/insights_commands/curl_-s_http_..169.254.169.254.latest.dynamic.instance-identity.document_--connect-timeout_5
dev/test-archives/core-base/meta_data/insights.specs.Specs.aws_instance_id_doc.json
src/puptoo/process/profile.py

Adding a check for marketplace codes in a system. If they exist, we mark this system as a marketplace one in system_profile
JIRA: RHCLOUD-12089

Add a check for AWS Marketplace

---

src/puptoo/process/profile.py

This reverts https://github.com/RedHatInsights/insights-puptoo/pull/134 based on the discussion from https://github.com/RedHatInsights/inventory-schemas/pull/54#issuecomment-804929609

Revert "profile: Enforce valid modes in selinux (#134)"

---

src/puptoo/process/profile.py

Alternative to https://github.com/RedHatInsights/insights-puptoo/pull/141

Use empty string for systems with no releasever

---

.gitignore
src/puptoo/process/profile.py
tests/test_installed_rpms.py

Remove gpg-pubkey packages from RPM lists.

---

poetry.lock

there are some system profile deps in this one

[core] update the version of core in puptoo

---

pr_check.sh

We need this for tests against system_profile to work

[fix] add filters disable to pr_check

---

poetry.lock
requirements.txt

[update] update jinja2 for sec vulnerability

---

deployment.yaml
pr_check.sh
unit_test.sh

This is to bring us in line with guidelines for bonfire/clowder dependency management
Depends on https://github.com/RedHatInsights/bonfire/pull/44

Add optional dependencies for ingress apps

---

src/puptoo/process/profile.py
tests/test_greenboot_status.py
tests/test_host_type.py

Depends on 
https://github.com/RedHatInsights/inventory-schemas/pull/61
https://github.com/RedHatInsights/inventory-schemas/pull/62
https://github.com/RedHatInsights/insights-host-inventory/pull/892
https://github.com/RedHatInsights/insights-host-inventory/pull/896

Add host_type and greenboot_status to system profile.

---

Dockerfile

[fix] modify haberdasher version

---

Dockerfile

[builds] set dockerfile to use ubi-minimal

---

Dockerfile

[fix] tar is missing from the build

---

src/puptoo/app.py

[fix] remove null values for display_name and ansible_host

---

src/puptoo/mq/consume.py
src/puptoo/mq/produce.py

[fix] Fix kafka config params

---

src/puptoo/app.py
src/puptoo/mq/consume.py
src/puptoo/mq/produce.py

The cacert value is the actual cert, while we need to just provide a
path

[fix] Fix cacert for kafka

---

src/puptoo/mq/produce.py

[fix] Fix bootstrap servers in produce function

---

src/puptoo/mq/consume.py
src/puptoo/mq/produce.py

[debug] Add print messages to consumer and producer

---

src/puptoo/app.py
src/puptoo/mq/consume.py
src/puptoo/mq/produce.py

[logging] log kafka connection_info

---

src/puptoo/app.py
src/puptoo/mq/consume.py
src/puptoo/mq/produce.py

[debug] Remove debug messages

---

Dockerfile

[feat] remove haberdasher

---

src/puptoo/utils/config.py
src/puptoo/utils/puptoo_logging.py

[debug] more kafka debugging

---

deployment.yaml

[template] update deployment template

---

src/puptoo/app.py
src/puptoo/mq/consume.py

[debug] print the cert

---

src/puptoo/app.py
src/puptoo/mq/consume.py
src/puptoo/utils/config.py

[fix] Remove debug items

---

src/puptoo/process/profile.py
tests/test_rpmostree_status.py

Inventory schema PR: https://github.com/RedHatInsights/inventory-schemas/pull/71
HBI PR: https://github.com/RedHatInsights/insights-host-inventory/pull/926

Add deployments from rpm ostree status to profile.

---

src/puptoo/process/profile.py
tests/test_rpmostree_status.py

Remove empty version from rpm_ostree data

---

poetry.lock
pyproject.toml
src/puptoo/utils/puptoo_logging.py

We removed haberdasher due to some performance issues. putting back in
direct logs to cloudwatch

[cloudwatch] re-add cloudwatch logging

---

dev/test-archives/core-base/data/insights_commands/ip_addr
src/puptoo/process/profile.py

Use the same regex to validate mac_addresses that inventory does. We've
had some issues where these come through incorrectly. The regex will
help

[fix] Check macs with regex

---

deployment.yaml

[fix] remove deprecated pods: clowder spec

---

src/puptoo/process/profile.py

there's another spot where mac addresses can get through unfiltered

[fix] filter mac addresses in facts

---

poetry.lock
pyproject.toml

The latest core has a few parser fixes we can take advantage of

[update] Update insights-core version

---

src/puptoo/process/profile.py
tests/test_cpuinfo.py

Sort the cpu_flags so they always show up in the same order
RHCLOUD-15265

[profile] sort cpu_flags

---

poetry.lock
pyproject.toml

[core] Update insights-core

---

src/puptoo/process/profile.py

Signed-off-by: Aditi Puntambekar <apuntamb@redhat.com>
EDIT - Adding @kgaikwad in loop for additional review.

Add RosConfig file check

---

deployment.yaml
src/puptoo/app.py
src/puptoo/mq/consume.py
src/puptoo/utils/config.py

[feat] Add malware detection payload handling

---

src/puptoo/app.py
src/puptoo/mq/msgs.py
src/puptoo/utils/puptoo_logging.py
tests/test_app.py
tests/test_msgs.py

ESSNTL-2767 Include org_id

---

dev/README.md
dev/docker-compose.yml
dev/full-stack.yml

Add static address:port to minio, create a new local minio bucket `insights-upload-puptoo`.
Ref card :  [https://issues.redhat.com/browse/ESSNTL-3277](https://issues.redhat.com/browse/ESSNTL-3277)

add insights-upload-puptoo bucket

---

tests/test_tags.py

Hopefully this will help with fixing tags formatting issues

Add unit tests for tags formatting

---

dev/test-archives/core-base/data/etc/yum.repos.d/redhat.repo
src/puptoo/process/profile.py

Adds `mirrorlist` of a yum repository into a System profile.
**Depends on https://github.com/RedHatInsights/inventory-schemas/pull/96**
VULN-2441

feat: add yum repo mirrolist to system profile

---

src/puptoo/process/profile.py

- See ESSNTL-3114 for context, I'd like to add the following new keys to the `system_profile`
- provider_id and provider_type
Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>

Add provider_id and provider_type to system_profile

---

src/puptoo/process/profile.py

Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>

fix: provider_type should be cloud_instance.provider

---

src/puptoo/process/profile.py

We'll get these two fields under canonical facts which are set by insights-core.
PR - [https://github.com/RedHatInsights/insights-core/pull/3654](https://github.com/RedHatInsights/insights-core/pull/3654)

Ref-ESSNTL-3114 remove provider_type and provider_id

---

build_deploy.sh
poetry.lock
pyproject.toml

Updating to the latest UBI8 Minimal and adding condition to build deploy script.

Security patching and updating build deploy script

---

build_deploy.sh

updating the build script to tag the date for security and compliance branch.

Updating Build Deploy Script

---

dashboards/grafana-dashboard-insights-puptoo-general.configmap.yaml

RHINENG-394 to show total number instead of mean value in Grafana

---

dashboards/grafana-dashboard-insights-puptoo-general.configmap.yaml
dev/cdappconfig.json
src/puptoo/utils/config.py

The Puptoo throws an error while objects upload to Minio when used as a container.
This bug is only on local and EE.

RHINENG-451 Fix redis implementation for Ephemeral and local env

---

deployment.yaml
src/puptoo/app.py
src/puptoo/utils/config.py

We should be able to skip redis with an environment variable if needed

setup a disable redis flag

---

src/puptoo/app.py
src/puptoo/utils/config.py

We should be able to use a REDIS password with SSL if it's provided.

feat: Enable redis SSL with auth capabilities

---

pyproject.toml

Resolve [RHINENG-8149](https://issues.redhat.com/browse/RHINENG-8149)

RHINENG-8149: setuptools vulnerability mitigation

---

src/puptoo/process/profile.py
tests/test_rpmostree_status.py

Continue of https://github.com/RedHatInsights/insights-puptoo/pull/323 for RHINENG-8752

Profile rpm ostree deployments

---

pyproject.toml
src/puptoo/process/profile.py
tests/test_rpmostree_status.py

Update security branch

---

src/puptoo/app.py
src/puptoo/utils/config.py

If redis has an ssl connection, we should be able to use it. This change allows both a redis SSL connection and the ability to disable redis if needed.

feat: Enable redis ssl

---

src/puptoo/process/profile.py

fix [RHINENG-467](https://issues.redhat.com/browse/RHINENG-467)

RHINENG-467: use specs parsers over Specs.content

---

dev/test-archives/core-base/data/insights_commands/yum_updates_list
dev/test-archives/core-base/meta_data/insights.specs.Specs.yum_updates.json
src/puptoo/process/profile.py
tests/test_yum_updates.py

fix [issue](https://redhat-internal.slack.com/archives/C02TWLQU6H5/p1724754920566889)

fix: populate full data for "yum_updates" field

---

README.md

rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED

fix: add maintainer username

---

deployment.yaml
renovate.json

Signed-off-by: Lizhong Chen <lichen@redhat.com>
rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED

fix: Update deploy image to konflux image

---

src/puptoo/process/profile.py
tests/test_aws_instance_id.py

Signed-off-by: Xiaoxue Wang <xiaoxwan@redhat.com>
rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED

RHINENG-13408: fix "is_marketplace" for aws instance

---

src/puptoo/app.py
src/puptoo/process/__init__.py
src/puptoo/utils/metrics.py

- fix double counted metric "puptoo_successful_extractions_total"
- extend metrics group "puptoo_messages_processed_*"

RHINENG-15104: fix and enhance metrics

---

src/puptoo/app.py
src/puptoo/process/__init__.py
src/puptoo/utils/metrics.py

- refine the metrics adjusting in last 2 commits 
- with no prometheus metric indicator naming changes for compatibility 
A comparation to commit https://github.com/RedHatInsights/insights-puptoo/commit/77888179147307e1109d660b4801120b3af45e61 :  https://github.com/RedHatInsights/insights-puptoo/compare/77888179147307e1109d660b4801120b3af45e61...JoySnow:insights-puptoo:metrics-adjust  
For RHINENG-15104, RHINENG-417

fix: rematching the metric counters

---

dashboards/grafana-dashboard-insights-puptoo-general.configmap.yaml

- apply time range variable in gauge panels

RHINENG-15876: add message processed panel in grafana

---

dev/test-archives/core-base/data/insights_commands/ps_auxcww
src/puptoo/process/profile.py
tests/test_ansible_info.py
tests/test_crowdstrike.py
tests/test_db_workloads.py
tests/test_intersystems.py
tests/test_mssql_info.py
tests/test_rhel_ai.py
tests/test_sap.py

- include the existing workload objects
- add new workload "ibm_db2" and "oracle_db"
Related schema changes at https://github.com/RedHatInsights/inventory-schemas/pull/148

RHINENG-15723: add unified entry "workloads" field to sp

---

dashboards/grafana-dashboard-insights-puptoo-general.configmap.yaml

fix: json format typos of grafana dashboard

---

.github/workflows/container-publish.yaml

RHINENG-18130: Fix publish workflow typo

---

src/puptoo/process/profile.py
tests/test_dnf_module_list.py

related schema change at: https://github.com/RedHatInsights/inventory-schemas/pull/160

RHINENG-19153: add "status" to "dnf_modules" sp fact

---

src/puptoo/app.py
src/puptoo/process/__init__.py
src/puptoo/utils/metrics.py
src/puptoo/utils/validators.py
tests/test_canonical_facts.py

- support canonical facts validation and error handlings for "compliance" and "malware-detection" services
- add metric counter "puptoo_messages_processed_failure_total"

RHINENG-18850: apply validateCanonicalFacts for all services
