app.py

This is a just a idea that I wanted to pass along.  This is not a PR that you must accept.  Its just food for thought...  :)
The idea here is to break the logic down into smaller chunks.  This should allow us to write tests for the individual chunks of logic.  This should allow us to build tests that send in valid data and invalid data into the individual methods and test the return values, exception, etc.
I think its also easier to follow the logic flow.  This allows me to follow the logic at a high level by using the names of the methods.  I can then step into the individual methods to dig into the lower level logic.
@SteveHNH let me know if you'd like to discuss, etc.

Move logic from main() method in to smaller methods

---

process.py

Small files do not properly fill the memory buffer and force a close()
To prevent this from breaking smaller archives, we need to add an
explicit flush before the file gets read.

Add a tempfile flush

---

process.py

We're going to call the tags "labels" in branch_info so as not to cause
conflicts with an incoming satellite tagging feature

Rename branch_info tags to labels

---

process.py

This is the first change necessary to remove archive re-processing from Vulnerabilities (https://github.com/RedHatInsights/vulnerability-engine/blob/master/listener/archive_parser.py).
And also removes this requirement from currently developed System Patch Management application
(https://github.com/RedHatInsights/patchman-engine)
Before this change, the installed_packages contained just a list of strings in `E:N-V-R` format.

Provide NEVRAs in system profile

---

process.py

Continues #35 for the same purpose. Just adds repo identifier to the repositories key, and adds code to parse DNF modules.
Inventory API schema modifications corresponding to this PR are here:
https://github.com/RedHatInsights/insights-host-inventory/pull/536

Add more repo information to system_profile

---

process.py

for example kernel packages can be installed in multiple versions and picking the highest version instead of first one found is useful for vulnerability and system patch management apps
or maybe better - all installed package versions should be stored, getting the highest version is only better than current state though, what do you think?

use latest version of package instead of first one

---

process.py

This commit pulls in the "captured_date" to the system profile. This
date corresponds to when a system profile's data was saved by the
client system.
For example, if a client tarball was created on a Monday and uploaded
on a Tuesday, this date would be Monday.

add "captured_date" to system profile

---

dev/full-stack.yml
process.py

The date_utc supplied by insights-core is TZ-naive (see
https://git.io/JvVeG). This commit adds the TZ info back onto the
datetime object before pulling the isoformat().
old format of `captured_date`: `2020-01-10T15:50:47`
new format of `captured_date`: `2020-01-10T15:50:47+00:00`
NOTE:  this commit also adds `inventory-rest` to the
`full-stack.yml`, which listens on port 8082. This is useful for
pulling system profiles during local testing to confirm they are
landing correctly.

add TZ to captured date

---

src/puptoo/process.py

Turn insights-core errors into strings so that they can be encoded as
JSON and properly sent to storage-broker

Fix bug in rejected payload reporting

---

src/puptoo/process.py

Previously, we were computing cores per socket as the number of cores
divided by the number of sockets. This is incorrect.
Instead, read the value off of the lscpu parser.

fix cores_per_socket computation

---

src/puptoo/app.py
src/puptoo/utils/metrics.py

We need this so that we can filter the payload-status topic out of the
messages

Add label for topic to produced messages

---

src/puptoo/process.py

Tags should be user defined, so we're relocing this to the
system_profile

relocate the location of SAP system key

---

src/puptoo/process.py

The namespace value isn't always there in tags.json. This covers that
issue

Fix tags parser of insights-client json

---

src/puptoo/process.py

There is a problem with the way we're grabbing this for hana instances
and it's blowing up in inventory.

Remove sap_version

---

src/puptoo/process.py

Some enabled_services end in '@' and some don't, this strips the '@'.

Remove the 'at' symbol in some enabled_services

---

build_deploy.sh

If we build with cache, we can miss updates to some of the underlying
python modules we need to install

Build with no-cache

---

setup.py
src/puptoo/process.py

This feature allows you to run puptoo's system_profile collection
against an archive without having to stand up an entire platform stack

feat: add ability to execute puptoo in shell

---

pr_check.sh

If the system_profile cannot be gathered during the test run, we want to
ensure that the PR check fails. This should give us a way to verify that
the specs being run are all accurate

fix: ensure pr_check fails if system_profile breaks

---

src/puptoo/app.py
src/puptoo/process.py
src/puptoo/utils/puptoo_logging.py

When a parser fails in system_profile we need to be able to easily
track down which one caused the problem. This new system will log each
parser when it fails and cause the payload to be rejected. We will be
able to search these failures with the request_id in kibana which will
help speed up troubleshooting time.

feat: improve puptoo parser logging

---

src/puptoo/utils/puptoo_logging.py

The filter for adding request_id and account to the logs was missing
from cloudwatch. Adding it so that we can search those fields in kibana

fix(logging): add context filter to cloudwatch logs

---

src/puptoo/process.py

The tuned parser was failing if tuned was not active on the system.
This should correct that behavior
BZ1893818

fix: tuned bug within system_profile

---

src/puptoo/process.py

The dmidecode parser may not include `bios` information, so we need to
check for that before attempted to get data from it.

fix: add check for dmidecode bios data

---

src/puptoo/process.py

The lscpu parser can fail on archives if `Cores per socket` is not a
key. Use `.get` to make it safer to run

fix: make lscpu parser more forgivable

---

deployment.yaml

Even though this may never be set to false, it is helpful to have it set
as a parm for consistency across apps.

Add CLOWDER_ENABLED param

---

deployment.yaml
src/puptoo/utils/config.py

The PR #77 that added dual support for clowder and legacy doesn't allow setting the env variable to anything that will result in False boolean value - any text string at all results in the variable in config.py being set to true.  This fixes that problem so only case-insensitive values of "true", "t", "yes", or "y" will result in the CLOWDER_ENABLED variable being set to True.  Any other value for the CLOWDER_ENABLED env var (or no value at all) will result in the variable being set to False.  Previously, the only way to get the variable set to false was to make sure no CLOWDER_ENABLED env var was defined, or it was set to an empty string.
Note this might be nice to apply to the DISABLE_PROMETHEUS variable as well as it will make the test for the env var value case insensitive and it adds …

Fix reading CLOWDER_ENABLED boolean env var so 'False' works as expected

---

src/puptoo/process.py

This workaround was added in response to:
https://issues.redhat.com/browse/HBISPSC-37
Once the inventory and schema PRs are merged, we can revert this change:
https://github.com/RedHatInsights/inventory-schemas/pull/39
https://github.com/RedHatInsights/insights-host-inventory/pull/773
*Only* merge this PR once the above two PRs are merged so as not to cause any errors.

Revert sap instances 98/99 workaround

---

pyproject.toml
src/puptoo/app.py
src/puptoo/process/__init__.py
src/puptoo/process/profile.py
src/puptoo/utils/config.py

- The process module contained logic for both the archive extraction and logic working with the system profile. Separated this into a submodule, where `profile.py` logic does not deal with archives, but instead only deals with invocation of insights-core rule, and subsequent data cleanup.
- The `process` module now only deals with working with archives, added new ContextManager, which does both downloading and extraction of the archives.
- Flake8 returned some errors, reformated some small amount of code.

Separate archive processing and system profile parsing, reformat according to flake8

---

src/puptoo/app.py

We can't use `None` in inventory. Need to not include this if it doesn't
exist

fix(sys_profile): Remove owner_id if empty

---

src/puptoo/app.py

Compliance payloads do not have system_profile so we have to make sure
we don't try to call it before sending to inventory. This will allow us
to only add owner ID to payloads with both an owner_id and a
system_profile

fix(compliance): Fix owner_id bug for compliance

---

src/puptoo/app.py
src/puptoo/process/profile.py

Depends on: https://github.com/RedHatInsights/insights-core/pull/2950
If the archive contains ROS data, we want to indicate that in the
platform_metadata. This is so that the ROS receiver can filter on
messages that only pertain to them, rather than fully processing all
insights archives.
RHCLOUD-12226

feat(system_profile): Add ROS check

---

src/puptoo/app.py

Since there is 4 hour drift on insights-client uploads. It's possible to
miss the window and have a system appear as stale. Increasing our
staletime to 29 hours should help avoid this.
RHCLOUD-12827

task: adjust staletime to 29 hours

---

src/puptoo/process/profile.py

We attempted to use the `rhsm` system fact from inventory, but upon investigation found that this fact is not provided by insights-puptoo. Added the system fact from the most likely source.

Add rhsm system fact parser

---

src/puptoo/process/profile.py

The releasever.set can be None. Need to only add it to the profile if
it's actually populated

fix: Releasever.set can be None

---

src/puptoo/process/profile.py

Inventory does not delete missing system facts, we need to send a `null` rhsm version if it is not available.

Also send null rhsm fact

---

src/puptoo/process/__init__.py
src/puptoo/utils/config.py
src/puptoo/utils/metrics.py

If we get archives with more than 1GB of unextracted data, we tend to
blow up in the engine. We should not be getting that much data at a
time. This adds a check of that unextracted file size and rejects any
archives that are too large.

[feat] add check of unextracted size

---

src/puptoo/process/profile.py

The HDB parser can sometimes present the data as a list and we need to
be able to handle situations where that happens
RHCLOUD-13341

[fix] Handle situation where HDB is a list

---

src/puptoo/process/profile.py

In order to wipe out tags when insights-client sends nothing,
we want to ensure that we send the empty dictionary so the tags go away.
RHCLOUD-13307

[fix] set insights-client tags to empty by default

---

src/puptoo/process/profile.py

[fix] last_boot_time should contain timezone info

---

src/puptoo/process/profile.py

Inventory only accepts strings, so we have to ensure that all tags are
strings. The downside is that some tags will be stripped out, but this
ensures that systems are able to register.

[fix] Remove values that are not strings from tags

---

src/puptoo/process/profile.py
tests/test_greenboot_status.py

Store in the profile whether greenboot detected an OS update rollback.
- [HBI PR](https://github.com/RedHatInsights/insights-host-inventory/pull/917)
- [Schema update](https://github.com/RedHatInsights/inventory-schemas/pull/66)

Add greenboot fallback detected bool to system profile.

---

src/puptoo/app.py
src/puptoo/process/profile.py

If we get a display_name or ansible hostname from metadata, we should
use it rather than the one we grab out of the archive. If it exists in
metadata, then the customer has set that manually and it should be
preferred.

[fix] set display_name and ansible_host from metadata

---

src/puptoo/process/profile.py
tests/test_lscpu.py

lscpu output on my aarch64 VM doesn't contain 'Cores per socket' line and puptoo throws a TB. There is 'Cores per cluster' instead.
https://github.com/karelzak/util-linux/blob/4cae2104ec88890e649b950283fe20af91e9c642/sys-utils/lscpu.c#L876
It would be better to support 'Cores per cluster' better, but it'd need more changes, also in frontend. At least fix the TB for now.

Fix TB when processing aarch64 system profile

---

src/puptoo/app.py
tests/test_clean_macs.py

There has been a report that we get invalid mac addresses through
canonical facts. We need to clean out certain mac_addresses that are not
valid so we can pass inventory schema.

[fix] clean invalid mac addresses

---

Dockerfile

Puptoo needs to have these in the image in order to extract these types
of files.

[fix] add xz and bzip2 to image

---

src/puptoo/mq/consume.py
src/puptoo/mq/produce.py

sasl.mechanisms should be plural

[fix] mistyped sasl mechanism config

---

src/puptoo/process/profile.py

An edge case where mac address is "none" would cuase puptoo to fail the
archive. We now check for that and handle it

[bug] Fix crash when mac address is "none"

---

src/puptoo/app.py
tests/test_clean_macs.py

Match mac addresses against regex to prevent bad macs from making it
into inventory via canonical facts

[fix] filter bad macs from canonical facts

---

src/puptoo/app.py

Since puptoo is running on the new ingress announce topic, we need to
make sure that it doesn't accept anemic tenants until the downstream is
ready for them. The announce topic could potentially send an account
without an EBS account number and currently most downstream services
require it.
This check can be removed when the full support is available downstream.

ESSNTL-2766 handle anemic-tenants

---

src/puptoo/process/profile.py

Insights parser might return `yum_repo_definition` dictionary without `name` key/property

ESSNTL-2893 Sort repos by ID

---

pyproject.toml
src/puptoo/mq/consume.py
src/puptoo/mq/produce.py

The sasl config needs to use the clowder config for the mechanism and
protocol
Signed-off-by: Stephen Adams <stephen.adams@redhat.com>

make kafka config pull values from clowder

---

src/puptoo/process/profile.py

PR addresses [ESSNTL-3550](https://issues.redhat.com/browse/ESSNTL-3550).
Instead of checking for string instances and ignoring other tags input, cast tags input as string for better user experience as numbers will not need to be wrapped in quotations when strings already do not need to be wrapped.
If there is a reason we would prefer not to do this, then we should alert the user with an appropriate error message instead as, though it is [documented](https://consoledot.pages.redhat.com/docs/dev/services/inventory.html#host-tags), it is not clear to users when in the process of adding tags.

[ESSNTL-3550] Cast tags as expected string values

---

src/puptoo/process/profile.py

With the recent change in https://github.com/RedHatInsights/insights-puptoo/pull/230 to cast tags as strings for better user experience around integer values, null values are now converted to string "None".
Instead, we should check for null values and use them and only cast to string in non-null cases.
This issue was reported here:
https://issues.redhat.com/browse/ESSNTL-3568

[ESSNTL-3568] Allow tags value null

---

src/puptoo/upload.py
src/puptoo/utils/config.py

We should add `AWS` to the storage config option variables in order to
ensure they these keys do not get printed to the logs on startup. The
following function removes any AWS related keys from the config
printout.
[config.py](https://github.com/RedHatInsights/insights-puptoo/blob/945dd86cbac1f563602e70c8d593e8b180a9c5cd/src/puptoo/utils/config.py#L16)
Signed-off-by: Stephen Adams <stephen.adams@redhat.com>

fix: prefix storage key config options

---

src/puptoo/process/profile.py
tests/test_host_type.py

* profile.py: moved the host_type edge profile from greenboot to ostree status check
Fixes: #240 
Signed-off-by: Jonathan Holloway <jholloway@redhat.com>

fix: move host_type edge dependency to rpm_ostree status

---

src/puptoo/process/profile.py

**Depends on https://github.com/RedHatInsights/inventory-schemas/pull/99**
Gathers `releasever` and `basearch` facts to system profile from `yum_updates`.
This is to properly identify YUM repository URLs. Especially those that
have `$releasever` and `$basearch` placeholders.
Note, that these two facts are already present in `yum_updates` JSON. However, the `yum_updates` requires additional parsing, hence this information should be globally present on system profile.
VULN-2456

feat: gather releasever and basearch

---

src/puptoo/process/profile.py

- See ESSNTL-3981 and ESSNTL-3939 for context
- this PR adds the `is_rhel` to the system_profile
Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>

Add `is_rhel` to system_profile

---

src/puptoo/process/profile.py

According to the discussion of ESSNTL-3939, the `is_rhel` will not be used by the Advisor UI, and does not need to insert into the puptoo `system_profile` as well.

Ref:ESSNTL-3114,ESSNTL-3939 Remove 'is_rhel'

---

deployment.yaml
pr_check.sh

We are archiving the iqe-e2e-plugin so the smoke tests we run as part of the PR CHECK job for puptoo have been moved to a new plugin: iqe-puptoo-plugin. This MR updates the PR_CHECK script to start using iqe-puptoo-plugin.

Update pr check to run tests from iqe-puptoo-plugin

---

deployment.yaml
src/puptoo/utils/config.py

Because of the way templates work, any string would evaluate to true. We need to check for the specific "true" flag

fix: Redis flag modification

---

src/puptoo/process/profile.py

- use safe get() calls instead of indexers  to avoid "KeyError"

RHINENG-8752: get value from deployments safely

---

src/puptoo/app.py

Start prometheus after the initiation of consumer and
producer to improve liveness and readiness probes.
More detail discussion is at [this doc comment thread](https://docs.google.com/document/d/1koa-4Bc2ib64uUdj0Tm_wbnuBvkrXnrQ7b4OIlZhd0U/edit?disco=AAABHBDaZOY).

RHINENG-415: tune the start time of prometheus

---

dev/test-archives/core-base/data/insights_commands/bootc_status_--json
src/puptoo/process/profile.py
tests/test_bootc_status.py

Based on the discussions in RHINENG-9246, populate the cachedUpdate data individually for "booted", "staged", "rollback" sections of `system_profile["bootc_status"]`.    
And no more setting data for `system_profile["bootc_status"]['cachedUpdated']` field.

RHINENG-9246: add bootc "cachedUpdated" to system_profile

---

pyproject.toml
requirements.txt

vulnerability mitigation for image `SECURITY SCAN` in quay.io, related to RHINENG-10128

chore: bump requests from 2.31.0 to 2.32.0

---

requirements.txt

Resolve package conflicts of `jinja2` bumping up in https://github.com/RedHatInsights/insights-puptoo/pull/336 CI Jenkins [run](https://ci.int.devshift.net/job/RedHatInsights-insights-puptoo-pr-check/362/console):  (Cover changes of https://github.com/RedHatInsights/insights-puptoo/pull/336)
```
10:57:32 ERROR: Cannot install MarkupSafe==1.1.1 and jinja2==3.1.4 because these package versions have conflicting dependencies.
10:57:32 
10:57:32 The conflict is caused by:
10:57:32     The user requested MarkupSafe==1.1.1
10:57:32     jinja2 3.1.4 depends on MarkupSafe>=2.0
```
Also, resolve the dependency conflicts of `requests` seeing in this [run](https://ci.int.devshift.net/job/RedHatInsights-insights-puptoo-pr-check/361/console):
```
10:36:29 ERROR: pip's dependency resolver does not …
```

fix: bump up versions of jinja2 and MarkupSafe

---

Dockerfile

To fix the error in https://github.com/RedHatInsights/insights-puptoo/pull/343/checks
ERROR: failed to solve: [registry.redhat.io/ubi8/ubi-minimal](http://registry.redhat.io/ubi8/ubi-minimal): failed to resolve source metadata for [registry.redhat.io/ubi8/ubi-minimal:latest](http://registry.redhat.io/ubi8/ubi-minimal:latest): failed to authorize: failed to fetch anonymous token: unexpected status from GET request
Using  [registry.access.redhat.com](http://registry.access.redhat.com/) as this repo do not need authorize.

fix: use the base image from registry.access.redhat.com

---

dev/io_test/consumer/Dockerfile
dev/io_test/producer/Dockerfile

- RHINENG-13513 
- This update is driven by the snyk vulnerability scanning fixes.

chore: use py3.11 as base for dev Dockerfiles

---

src/puptoo/process/profile.py
tests/test_sap.py

The old SAP-related fields[1] will be removed in favor of the "sap" object[2]. Thus, this PR addresses RHINENG-2450.
For information, the pull request removing these old fields is [3][RHINENG-2286].
[1] - https://github.com/RedHatInsights/inventory-schemas/blob/master/schemas/system_profile/v1.yaml#L511-L534
[2] - https://github.com/RedHatInsights/inventory-schemas/blob/master/schemas/system_profile/v1.yaml#L483-L510
[3] - https://github.com/RedHatInsights/inventory-schemas/pull/119

RHINENG-2450 Remove logic about the old SAP-related fields

---

src/puptoo/process/profile.py
tests/test_sap.py

This reverts commit a0782b4de68fbf7a892be27dc0d13455cb7d927f.
It breaks Advisor, malware, patch and vulnerability.

Revert "RHINENG-2450 Remove logic about the old SAP-related fields"

---

dev/test-archives/core-base/data/insights_commands/lspci_-k
dev/test-archives/core-base/data/insights_commands/lspci_-vmmkn
dev/test-archives/core-base/meta_data/insights.specs.Specs.lspci.json
dev/test-archives/core-base/meta_data/insights.specs.Specs.lspci_vmmkn.json
src/puptoo/process/profile.py
tests/test_rhel_ai.py

Merge after inventory-schema fields adding: https://github.com/RedHatInsights/inventory-schemas/pull/144

RHINENG-13952: add rhel ai gpu model fields to sp

---

README.md

To avoid including the `./dev/test-archives/` directory layers in the generated test-archive. Archive with extra directory layers will result in processing failure in insights-engine service.

chore: enhance README.md for test-archive sample

---

src/puptoo/app.py
src/puptoo/utils/metrics.py

to enable the success/failure counting on all service types processing with new metrics group:
- total: `"puptoo_messages_consumed_total"`
- success:  `"puptoo_messages_consumed_success_total"`
- failure: do the math with `"puptoo_messages_consumed_total" - "puptoo_messages_consumed_success_total"`

RHINENG-417: enhance metrics to track for all services

---

.github/workflows/renovate-validator.yaml
renovate.json

- update schedual time
- add packageRules
- add github action - renovate-validator 
To fix for "No more new auto PRs for tekton updates, and leads to konflux pipeline failure" issue

ci: update renovate config and add renovate-validator

---

src/puptoo/app.py
src/puptoo/utils/config.py

- The upload of yum_updates data to s3 is only used by a specific service, if that service isn't deployed its unnecessary to configure an s3 bucket and store this data as it will not be used.

Add the ability to disable s3 uploads

---

src/puptoo/utils/puptoo_logging.py

After bump up the watchtower and its dependencies versions, the stage
pod failed to start and log with erorr "unexpected keyword argument
'boto3_session'". Changelog for watchtower shows that the Boto3
sessions passing ability was removed since v2.0.0. Fix for the
watchtower.CloudWatchLogHandler() args passing as we are on v3.4.0.
The former watchtower bump up PR:  https://github.com/RedHatInsights/insights-puptoo/pull/437 
serve RHINENG-11300

fix: arg passing in CloudWatchLogHandler

---

src/puptoo/process/profile.py
tests/test_dnf_module_list.py

- When fact "dnf_modules" get an empty list value after calculation, report the fact to Inventory instead of dropping it, as Inventory request it to override the existing value.
- Intro BYPASS_PROFILE_SANS_NONE_FACTS to bypass the profile_sans_none filtering on profile result
- Require to take care of the empty values case by case when adding new facts to profile

RHINENG-16233: allow an empty list value for "dnf_modules"

---

src/puptoo/process/profile.py
tests/test_bootc_status.py
tests/test_system_update_method.py

With this feat, `system_profile.system_update_method` would support for the following values: 
- RHEL 6 & 7 - yum
- RHEL 8 & 9 - dnf
- Edge - rpm-ostree
- Image Mode (RHEL AI) - bootc

RHINENG-15771: bootc update_method for image mode systems

---

src/puptoo/app.py

For known consumer poll error cases SESSTMOUT and MAXPOLL. When these
kafka consumer group connection errors happens, puptoo will break the
endless loop for continuing msg polling, and exit the process. This
allows the Kubernetes to recreate a new pod on behalf.

RHINENG-16129: pod exit on kafka consumer poll errors
